name: Delete ghcr.io images
description: |
  Delete container images from ghcr.io.
author: frantjc
branding:
  color: red
  icon: box
inputs:
  token:
    description: |
      GitHub token to authenticate with. Must have read:packages and delete:packages scopes.
    default: ${{ github.token }}
  images:
    description: |
      Images to delete from ghcr.io.
    required: true
runs:
  using: node20
  main: ../dist/ghcr-delete-images/index.js
