name: CI
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - cache-docker-volume/**
      - helm-package-push/**
      - ghcr-delete-images/**
      - setup-tool/**
      - testdata/charts/**
  pull_request:
    branches:
      - main
jobs:
  setup-tool:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./setup-tool
        with:
          repository: fluxcd/flux2
          version: v2.7.3
          tool: flux
      - run: flux --version
      - uses: ./setup-tool
        with:
          repository: dagger/dagger
      - uses: ./setup-tool
        with:
          repository: dagger/dagger
      - run: dagger version
      - uses: ./setup-tool
        with:
          repository: mikefarah/yq
          version: v4.48.2
      - uses: ./setup-tool
        with:
          repository: mikefarah/yq
          version: v4
      - run: yq --version
      - uses: ./setup-tool
        with:
          repository: go-task/task
          version: v3
      - run: task --version
  helm-package-push-cm:
    services:
      cm:
        image: chartmuseum/chartmuseum
        ports:
          - 8080:8080
        env:
          DEBUG: "1"
          STORAGE: local
          STORAGE_LOCAL_ROOTDIR: /tmp
        options: >-
          --health-cmd "sh -c 'wget -qSO- http://localhost:8080/health'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v4
        with:
          version: v3.19.3
      - uses: ./helm-package-push
        with:
          chart-path: testdata/charts/valid
          repository: cm://localhost:8080/
          dependency-update: false
          version: 0.1.0-ndu
        env:
          HELM_REPO_USE_HTTP: "true"
      - uses: ./helm-package-push
        with:
          chart-path: testdata/charts/valid
          repository: cm://localhost:8080/
          version: 0.1.0-du
        env:
          HELM_REPO_USE_HTTP: "true"
      - uses: ./helm-package-push
        continue-on-error: true
        with:
          chart-path: testdata/charts/valid-dependency
          repository: cm://localhost:8080/
          dependency-update: false
        env:
          HELM_REPO_USE_HTTP: "true"
      - uses: ./helm-package-push
        with:
          chart-path: testdata/charts/valid-dependency
          repository: cm://localhost:8080/
        env:
          HELM_REPO_USE_HTTP: "true"
      - uses: ./helm-package-push
        continue-on-error: true
        with:
          chart-path: testdata/charts/invalid-dependency
          repository: cm://localhost:8080/
        env:
          HELM_REPO_USE_HTTP: "true"
  helm-package-push-oci-and-ghcr-delete-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v4
      - uses: ./helm-package-push
        id: ghcr
        with:
          chart-path: testdata/charts/valid
          repository: oci://ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - uses: ./ghcr-delete-images
        with:
          tags: |
            ghcr.io/${{ github.repository }}/${{ steps.ghcr.outputs.name }}:${{ steps.ghcr.outputs.version }}
          token: ${{ secrets.GH_PAT }}
  cache-docker-volume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./cache-docker-volume
        id: cache
        with:
          volume: test
          key: cache-docker-volume-test
      - if: steps.cache.outputs.cache-hit == 'true'
        run: |
          content=$(docker run --rm -v test:/volume alpine cat /volume/hello.txt)
          [ "$content" = "hello there" ]
      - run: docker run --rm -v test:/volume alpine sh -c 'echo "hello there" > /volume/hello.txt'
