name: CI
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - dist/**
      - helm-package-push/**
      - ghcr-delete-images/**
      - package*.json
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - uses: ./helm-package-push
        id: chart
        with:
          chart-path: testdata/chart
          repository: oci://ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - uses: ./ghcr-delete-images
        with:
          images: |
            ghcr.io/${{ github.repository }}/${{ steps.chart.outputs.name }}:${{ steps.chart.outputs.version }}
          token: ${{ secrets.GH_PAT }}
