name: CI
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - helm-package-push/**
      - ghcr-delete-images/**
      - testdata/charts/**
  pull_request:
    branches:
      - main
jobs:
  ci:
    services:
      cm:
        image: chartmuseum/chartmuseum
        ports:
          - 8080:8080
        env:
          DEBUG: "1"
          STORAGE: local
          STORAGE_LOCAL_ROOTDIR: /tmp
        options: >-
          --health-cmd "sh -c 'wget -qSO- http://localhost:8080/health'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      - uses: ./helm-package-push
        id: ghcr
        with:
          chart-path: testdata/charts/valid
          repository: oci://ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - uses: ./ghcr-delete-images
        with:
          tags: |
            ghcr.io/${{ github.repository }}/${{ steps.ghcr.outputs.name }}:${{ steps.ghcr.outputs.version }}
          token: ${{ secrets.GH_PAT }}
      - uses: ./helm-package-push
        with:
          chart-path: testdata/charts/valid
          repository: cm://localhost:8080/
          dependency-update: false
          version: 0.1.0-ndu
        env:
          HELM_REPO_USE_HTTP: "true"
      - uses: ./helm-package-push
        with:
          chart-path: testdata/charts/valid
          repository: cm://localhost:8080/
          version: 0.1.0-du
        env:
          HELM_REPO_USE_HTTP: "true"
      - uses: ./helm-package-push
        continue-on-error: true
        with:
          chart-path: testdata/charts/valid-dependency
          repository: cm://localhost:8080/
          dependency-update: false
        env:
          HELM_REPO_USE_HTTP: "true"
      - uses: ./helm-package-push
        with:
          chart-path: testdata/charts/valid-dependency
          repository: cm://localhost:8080/
        env:
          HELM_REPO_USE_HTTP: "true"
      - uses: ./helm-package-push
        continue-on-error: true
        with:
          chart-path: testdata/charts/invalid-dependency
          repository: cm://localhost:8080/
        env:
          HELM_REPO_USE_HTTP: "true"
